[package]
name = "bandcamp-daily-fetcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
musicbrainz_rs = { version = "0.5.0", default-features = false, features = ["async"] }
rspotify = "0.13.0"
scraper = "0.19.0"
serde = "1.0.197"
serde_json = "1.0.114"
